language: cpp
compiler: gcc
install: sudo apt-get install libsdl1.2-dev libboost-dev libboost-system-dev -y; sudo pip install cpp-coveralls --use-mirrors
script: cd src; make
after_success: coveralls --exclude lib --exclude tests
